# Generated by Django 2.2.3 on 2020-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bannervideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannervideo',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='bannervideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
