# Generated by Django 2.2.3 on 2020-01-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200110_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannervideo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
