# Generated by Django 2.2.3 on 2020-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bannervideo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannervideo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
