# Generated by Django 2.2.3 on 2020-01-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200129_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='dominion',
        ),
    ]
