# Generated by Django 2.2.3 on 2020-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_platform_dominion'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='dominion',
            field=models.CharField(default='Lutheran', max_length=100),
        ),
    ]
