# Generated by Django 2.2.3 on 2020-01-29 09:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_platform_dominion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(choices=[(0, 'NO'), (1, 'YES')])),
                ('title', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('organiser', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('church', models.ManyToManyField(to='home.Platform')),
            ],
        ),
    ]
