# Generated by Django 2.2.3 on 2020-01-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_denomination'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastorsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChurchDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Platform')),
                ('pastor_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pastor',
            },
        ),
    ]
