# Generated by Django 2.2.3 on 2020-01-29 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_pastorsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_title', models.CharField(choices=[('mch', 'Mchungaji Kiongozi'), ('mch1', 'Mchungaji Msaidizi'), ('mwnj', 'Muinjilisti'), ('mz', 'Mzee wa Kanisa'), ('mzf', 'Mzee wa kanisa/Mama')], max_length=255)),
                ('a_leader_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Platform')),
                ('leader_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leader ',
            },
        ),
    ]
