# Generated by Django 2.2.3 on 2020-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_leaderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderdetails',
            name='leader_title',
            field=models.CharField(choices=[('Mchungaji Kiongozi', 'Mchungaji Kiongozi'), ('Mchungaji Msaidizi', 'Mchungaji Msaidizi'), ('Muinjilisti', 'Muinjilisti'), ('Mzee wa Kanisa', 'Mzee wa Kanisa'), ('Mzee wa kanisa/Mama', 'Mzee wa kanisa/Mama')], max_length=255),
        ),
    ]
