# Generated by Django 2.2.3 on 2020-02-14 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20200129_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denomination',
            name='users',
        ),
        migrations.AddField(
            model_name='denomination',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
