# Generated by Django 3.0.3 on 2020-02-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200214_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='feed_image')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')])),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Platform')),
            ],
        ),
    ]
