# Generated by Django 3.0.3 on 2020-02-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200219_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_list',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
